server:
  port: 8089

spring:
  elasticsearch:
    uris: http://elasticsearch:9200
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: audit-log-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
