server:
  port: 8083

spring:
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: neo4jpassword
  data:
    neo4j:
      database: neo4j
  datasource:
    url: jdbc:postgresql://postgres:5432/atlas_connection
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
