apiVersion: v1
kind: Secret
metadata:
  name: atlas-secrets
  namespace: default
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNzcGFzc3dvcmQ= # base64 for postgrespassword
  NEO4J_PASSWORD: bmVvNGpwYXNzd29yZA== # base64 for neo4jpassword
  JWT_SECRET: NTM2NzU2NkI1OTcwMzM3MzM2NzYzOTc5MkY0MjNGNDUyODQ4MkI0RDYyNTE2NTU0Njg1NzZkNUE3MTM0NzQzNw== # base64 for token secret
  HUGGINGFACE_API_TOKEN: aGZfbW9ja190b2tlbl9mb3JfbG9jYWxfdGVzdGluZw== # base64 for hf_mock_token_for_local_testing
